AddEventHandler('onClientMapStart', function()
  exports.spawnmanager:setAutoSpawn(true)
  exports.spawnmanager:forceRespawn()
  TriggerServerEvent('osi:server:Notify', {msg: "onClientMapStart"})
end)
